### ISSUE TITLE
the font size for the normal text for content is to thin

### ISSUE THREAD

**Issue by hong-tm** [TriDiamond/Obsidian-Obsidianite#4]
![Snipaste_2020-11-07_23-56-33](https://user-images.githubusercontent.com/51999870/98445857-0c771680-2155-11eb-81e3-ed507148cc23.png)
can try to use the another type of font in glowsansc and make font bigger and bolder, to get a confortable view.tq.

**Comment by TriDiamond** [comment]
This got me thinking, the theme has to take consider of English language or other languages, so boldness or font-size need to be reconsidered for all. But I do have an idea of having an isolated area for tweaking the theme's main variables at the beginning of the css file. So users can tweak the theme with ease! Will work on this one for sure!

**Comment by hong-tm** [comment]
@TriDiamond  keep going on, hope to get better and better

**Comment by TriDiamond** [comment]
@hong-tm text weight has changed to 450, you can also edit it yourself in the obsidian.css file. Please update to the latest version.

For the font settings, change here:

```css
:root {
  /***************************************/
  /*    FONTS RELATED                    */
  /***************************************/

  /** Font Customization **/
  --default-font: 'Rubik', 'Glow Sans SC', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI',
    Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', sans-serif;

  /** Main text font weight **/
  --body-font-weight: 450;

  /** Font family for hash-tags **/
  --tag-font-family: 'OperatorMonoSSmLig-Book', 'Glow Sans SC', '华文细黑', 'STXihei', 'PingFang TC',
    '微软雅黑体', 'Microsoft YaHei New', '微软雅黑', 'Microsoft Yahei', '宋体', 'SimSun',
    'Helvetica Neue', 'Helvetica', Arial, sans-serif !important;
}
```
