### ISSUE TITLE
Text isn't properly formatted in certain situations

### ISSUE THREAD

**Issue by reallyely** [TriDiamond/Obsidian-Obsidianite#7]
Great theme! Thanks for your hard work.

Windows 10, Obsidian 0.9.11, Obsidianite (Dark and Light Mode)

Two Issues I've run into so far

![image](https://user-images.githubusercontent.com/1640588/98671396-2e71c400-2322-11eb-9780-f7aaaf41de22.png)
When a link is also bold, the text clipping appears to be unset.

![image](https://user-images.githubusercontent.com/1640588/98672003-18b0ce80-2323-11eb-9d77-deeaf7133e51.png)
Italicized text is forced to Operator Mono, but should fall back to Rubik as it's the free and recommended default font on your readme.

**Comment by TriDiamond** [comment]
The first issue bold formatting with links, I am still trying to find a way to fix that one. So it will be fixed sooner or later. For now try to not use bold formatting for links yet.

For the second issue, I will fix that in 1.1.1, what you suggests makes perfect sense. Thanks for reporting!

**Comment by zcysxy** [comment]
@bennyxguo I think I fixed this using `:not()` pseudo-class.

```css
.cm-strong:not(.cm-hmd-barelink):not(.cm-hmd-internal-link):not(.cm-highlight),
strong {
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  padding: 0 0.1rem;
  color: #7aa2f7;
  background-color: #7aa2f7;
  background-image: linear-gradient(62deg, #87c2fd 0%, #dcb9fc 100%) !important;
}
```

I just exclude `[]`, wikilinks and highlight for now, maybe there are some other inline formats should be excluded.
